import { DIFFICULTY_REWARDS } from './xpCurve.js'

// Habits are now "Quests" — same underlying data, richer model.
// icon/iconColor/iconBg are string keys resolved to lucide components
// in a small registry (see iconRegistry.js) so this file stays plain data
// and is easy to persist / regenerate.
//
// `kind`: 'habit' (recurring, tracked with streaks) | 'task' (one-off)
// `trackingType`: 'tick' (checkbox) | 'timer' (count up to a duration)
//                 | 'numeric' (log a value up to a target, any unit)
export const initialHabits = [
  {
    id: 1,
    title: 'Read 20 pages',
    description: 'Feed your mind before the day gets loud.',
    category: 'Learning',
    difficulty: 'Medium',
    frequency: 'Daily',
    timeEstimate: '20 min',
    icon: 'BookOpen',
    color: 'purple',
    kind: 'habit',
    trackingType: 'tick',
    timerTargetSeconds: 600,
    timerElapsedSeconds: 0,
    numericTarget: 20,
    numericUnit: 'pages',
    numericValue: 0,
    done: false,
    currentStreak: 4,
    longestStreak: 9,
    totalCompletions: 41,
    ...DIFFICULTY_REWARDS.Medium,
  },
  {
    id: 2,
    title: 'Drink water',
    description: 'Stay sharp. Stay hydrated.',
    category: 'Health',
    difficulty: 'Easy',
    frequency: 'Daily',
    timeEstimate: 'All day',
    icon: 'Droplet',
    color: 'blue',
    kind: 'habit',
    trackingType: 'numeric',
    timerTargetSeconds: 600,
    timerElapsedSeconds: 0,
    numericTarget: 8,
    numericUnit: 'glasses',
    numericValue: 3,
    done: false,
    currentStreak: 12,
    longestStreak: 12,
    totalCompletions: 58,
    ...DIFFICULTY_REWARDS.Easy,
  },
  {
    id: 3,
    title: 'Deep work session',
    description: 'Forge discipline through focus.',
    category: 'Discipline',
    difficulty: 'Hard',
    frequency: 'Daily',
    timeEstimate: '25 min',
    icon: 'Brain',
    color: 'orange',
    kind: 'habit',
    trackingType: 'timer',
    timerTargetSeconds: 1500,
    timerElapsedSeconds: 480,
    numericTarget: 10,
    numericUnit: 'reps',
    numericValue: 0,
    done: false,
    currentStreak: 3,
    longestStreak: 15,
    totalCompletions: 33,
    ...DIFFICULTY_REWARDS.Hard,
  },
  {
    id: 4,
    title: 'Clean room',
    description: 'A clear space, a clear mind.',
    category: 'Discipline',
    difficulty: 'Easy',
    frequency: 'Weekly',
    timeEstimate: '15 min',
    icon: 'Sparkles',
    color: 'teal',
    kind: 'habit',
    trackingType: 'tick',
    timerTargetSeconds: 600,
    timerElapsedSeconds: 0,
    numericTarget: 10,
    numericUnit: 'reps',
    numericValue: 0,
    done: false,
    currentStreak: 1,
    longestStreak: 4,
    totalCompletions: 9,
    ...DIFFICULTY_REWARDS.Easy,
  },
  {
    id: 5,
    title: 'Finish portfolio README',
    description: 'One-off task — no streak, just get it done.',
    category: 'Career',
    difficulty: 'Medium',
    frequency: 'Once',
    timeEstimate: '30 min',
    icon: 'Pencil',
    color: 'purple',
    kind: 'task',
    trackingType: 'tick',
    timerTargetSeconds: 600,
    timerElapsedSeconds: 0,
    numericTarget: 10,
    numericUnit: 'reps',
    numericValue: 0,
    done: false,
    currentStreak: 0,
    longestStreak: 0,
    totalCompletions: 0,
    ...DIFFICULTY_REWARDS.Medium,
  },
]

export const initialPlayer = {
  level: 8,
  xp: 680, // progress within current level
  totalXpEarned: 3260,
  coins: 420,
  energy: 80,
  health: 100,
  currentStreak: 12,
  longestStreak: 18,
  xpMultiplier: 1,
  name: 'Jay',
}
